default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: app_test

# This makes Rails respect the .env database config inside Docker.
production:
  url: <%= ENV["DATABASE_URL"] %>